# Generated by Django 3.0.5 on 2020-05-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200518_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='document/')),
                ('message', models.TextField()),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 17, 18, 28, 468527))),
            ],
        ),
    ]
