# Generated by Django 3.0.5 on 2020-05-22 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200522_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 16, 3, 0, 438762)),
        ),
    ]
