# Generated by Django 3.0.5 on 2020-05-26 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200522_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 22, 18, 17, 321969)),
        ),
    ]
